apiVersion: v1
kind: Service
metadata:
  name: magento2
  labels:
    app: magento2
spec:
  ports:
    - port: 80
  selector:
    app: magento2
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mg-pv-claim
  labels:
    app: magento2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: magento2
  labels:
    app: magento2
spec:
  selector:
    matchLabels:
      app: magento2
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento2
        tier: frontend
    spec:
      containers:
      - image: tiniherodev/magento2.4:apache2-php-7.4-mysqli-dev
        name: magento2
        command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        env:
        - name: MAGENTO_DB_HOST
          value: wordpress-mysql
        - name: MAGENTO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: magento2
        volumeMounts:
        - name: magento2-persistent-storage
          mountPath: "/data"
      volumes:
      - name: magento2-persistent-storage
        persistentVolumeClaim:
          claimName: mg-pv-claim
